In [4]:
import numpy as np

myarr = np.array([3,6,32,7])
print(myarr)

[ 3  6 32  7]


In [5]:
#0-D array

a = np.array(42)
print(a)

42


In [6]:
#1-D array

b = np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [7]:
#2-D array 

c = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[0,1,2]]])
print(c)

[[[1 2 3]
  [4 5 6]]

 [[7 8 9]
  [0 1 2]]]


In [8]:
#to get the dimension of array

print(myarr.ndim)
print(a.ndim)
print(b.ndim)
print(c.ndim)

1
0
2
3


In [9]:
#to know the type of array

print(type(a))
print(type(b))
print(type(c))
print(type(myarr))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [10]:
r = np.array([10,20,30,40,50])
print(r)


#as array usage
#create n dim array with this
res = np.asarray(r,dtype="float",order="C")
print(res)

#to check iter
for i in np.nditer(res):
    print(i)

[10 20 30 40 50]
[10. 20. 30. 40. 50.]
10.0
20.0
30.0
40.0
50.0


In [11]:
#iter funtion

t = np.array([[10,20,30],[40,50,60]])
print(t)

res1 = np.asarray(t,dtype="int",order="F")

#to check iter
for i in np.nditer(res1):
    print(i)

[[10 20 30]
 [40 50 60]]
10
40
20
50
30
60


In [12]:
#b will take letters as bytes

#buffer function
s = b"hello welcome to python"
res2 = np.frombuffer(s, dtype='S1', count=10, offset=0)
print(res2)


[b'h' b'e' b'l' b'l' b'o' b' ' b'w' b'e' b'l' b'c']


In [13]:
#iter function
list = [345,45,356,47,567,34,634,5]
d = np.fromiter(list,dtype="float",count=-1)
print(d)

[345.  45. 356.  47. 567.  34. 634.   5.]


In [27]:
#slicing

arr = np.array([[[10,20,30],[40,50,60],[70,80,90]]])
print(arr[0:2])


[[[10 20 30]
  [40 50 60]
  [70 80 90]]]
